export { default as UserRoutes } from "./userRoutes";
export { default as addressRoutes } from "./addressRoutes";
export { default as categoryRoutes } from "./categoryRoutes";
export { default as productRoutes } from "./productRoutes";
export { default as uploadRoutes } from "./uploadRoutes";
export { default as colorRoutes } from "./colorRoutes";
export { default as badgesRoutes } from "./badgeRoutes";
export { default as cartRoutes } from "./cartRoutes";
export { default as orderRoutes } from "./orderRoutes";
